### ISSUE TITLE
on_uninstall, do_background_checks is too generic global functions

### ISSUE THREAD

**Issue by Ciantic** [maksuturva/woocommerce_payment_module#1]
I'm reviewing the plugin, there are few problems immediately:

In WordPress all plugins share a namespace (root namespace) and all function names should be unique. I propose renaming all functions e.g. `on_uninstall` to `maksuturva_on_uninstall` etc.

The plugin behaves incorrectly if *any* of the WordPress plugins has same named functions, and this is important.

**Comment by maksuturva** [comment]
Many thanks!
We'll fix this as soon as possible.

**Comment by soderluk** [comment]
This has been fixed now in 2.0.0
