### ISSUE TITLE
Warning & Fatal error

### ISSUE THREAD

**Issue by markerdev** [maksuturva/woocommerce_payment_module#11]
When activating the plugin and then going to woocommerce settings, i get this error.

Warning: require_once(class-wc-order-compatibility-handler.php ): failed to open stream: No such file or directory in ... in class-wc-gateway-implementation-maksuturva.php on line 33

Fatal error: require_once(): Failed opening required 'class-wc-order-compatibility-handler.php ' (include_path='.:/ ... in class-wc-gateway-implementation-maksuturva.php on line 33

I tried earlier the old plugin but removed it before activating this new version as said in the docs 5.1

Am i doing something wrong?

**Comment by solid-ahlholm** [comment]
Hi,
I will look into this. Sounds like the files that should handle compatibility between WooCommerce 2.* and 3.* are missing.

**Comment by markerdev** [comment]
Hi,

Okey, thanks!

**Comment by solid-ahlholm** [comment]
Problem found. There was an extra space at the end of an include statement which Windows didn't mind but Linux did. We will run a more thorough test on Linux now to really confirm that everything works as it should.

**Comment by markerdev** [comment]
Oh, how typical :D 

Okey. I will wait until youre ready with testing. Thanks for the quick reaction to fix the bug!

**Comment by Hene-Svea** [comment]
Fixed. Closing the issue now.
