### ISSUE TITLE
Redirect on order received page fails

### ISSUE THREAD

**Issue by bjork** [maksuturva/woocommerce_payment_module#2]
I was trying the 2.0 version briefly and had an issue. One can proceed from this order received page by clicking Maksuturva, but it is not very user friendly. There was a JavaScript error on the console, but unfortunately I did not remember to log that. But seemed to be the result of missing redirect url in a data attribute.

<img width="660" alt="screen shot 2016-03-16 at 20 35 21" src="https://cloud.githubusercontent.com/assets/102611/13824953/e6097f3c-ebb8-11e5-8c8e-e45810c2e8e0.png">

This issue is a bit short on details I'm afraid due to time constraints. I try my best to answer any questions you might have.

**Comment by kryysler** [comment]
Thank you for you're interest and for pointing out this issue. We have released a new version (2.0.1), which includes a fix for this. Feel free to download it and try it out.
