### ISSUE TITLE
Support for custom reference numbers

### ISSUE THREAD

**Issue by iraudasoja** [maksuturva/woocommerce_payment_module#49]
I didn't found hooks (or any other way) to set up custom reference number for the payment (`pmt_reference`). 

Is it possible to use own references for the payments?

If not, I would like to see it to added to your task list.

---------- Editing: Some testing done ----------------

Following filter could help to set up a custom reference number.

[class-wc-gateway-implementation-maksuturva.php#L167](https://github.com/maksuturva/woocommerce_payment_module/blob/master/includes/class-wc-gateway-implementation-maksuturva.php#L167)

```return apply_filters( 'maksuturva/payment_data', $data );```

**Comment by Svea-Maintainer** [comment]
Thank you for your feature request. Currently the reference number is based on this calculation, added with check number.
https://github.com/maksuturva/woocommerce_payment_module/blob/master/includes/class-wc-gateway-implementation-maksuturva.php#L544

Do you have a specific algorithm in mind or plugin that generates a set of numbers for this use? Or do you want to add prefix for example to the reference number?

**Comment by iraudasoja** [comment]
Our use case is that reference numbers have to be in given number space, for example 40 000 000 - 49 999 999.

These reference numbers are generates by our WP-site, and it is responsible to generates valid Finnish references.

Then we can set the custom reference to the payment and it will override Maksuturva default generated reference.

**Comment by iraudasoja** [comment]
Tervehdys, 

meidän kannalta vaihtoehto seuraava vaihtoehto olisi paras.

c) Pohjanumero esim. 4000017 muodostetaan toisaalla ja annetaan Svea Maksuturva -pluginille hooksin välityksellä. Svea Maksuturva -plugin laskee pohjanumerolle tarkisteen ja käyttää tätä maksun viitteenä (pmt_reference).

Tämä saavutettaisiin siten, että tuohon private-funktioon lisättäisiin paluuksi esim. `apply_filters( 'maksuturva/internal_payment_id', $order_handler->get_id() + 100 );`

```php
private function get_internal_payment_id( WC_Order $order ) {
        $order_handler = new WC_Order_Compatibility_Handler( $order );
        return apply_filters( 'maksuturva/internal_payment_id', $order_handler->get_id() + 100 ); // Tämä oli ennen "return $order_handler->get_id() + 100;"
}
```

Sitten meidän sivustolla annettaisiin haluttu pohjanumero seuraavalla tavalla.

```php
add_filter( 'maksuturva/internal_payment_id', function( $value) use ( $order_id ) {
    $payment_id =$this->create_payment_id( $order_id ); // Palauttaa 4000017
    if ( ! empty(  $payment_id ) {
        return $payment_id
    }

    return $value;
}
```

**Comment by Svea-Maintainer** [comment]
Ok, tämä selvä. Lähdetään katsomaan tällä ratkaisulla eteenpäin ja tuollaisessa muutoksessa ei näytä olevan tosiaan vaaraa taaksepäin yhteensopivuuden rikkoontumisesta. Teemme muutoksen ja testaamme. Palataan asiaan (pian) ja pääsette kokeilemaan tuota filtterin lisäämistä...

**Comment by Svea-Maintainer** [comment]
Now the requested feature has been implemented to the version 2.3.3 and ready for use.
https://github.com/maksuturva/woocommerce_payment_module/releases/tag/2.3.3

Once more, thank you for your feedback!

**Comment by iraudasoja** [comment]
Pääsin vasta nyt implementoimaan tätä viitenumeron kustomointia ja törmäsin ongelmaan verkkomaksun paluussa.

Lisäosa on toteutettu niin, että Woocommerce-tilaus haetaan payment_id:n perusteella. (`WC_Gateway_Maksuturva::load_order_by_pmt_id` Koska filtteri muokkaa payment_id:tä, käy niin, että tilausta ei löydy ja käyttäjälle näytetään virhe 'Missing reference number in response.'

Pahoittelen, että alunperin antamani ratkaisuehdotus ei siis toiminut oikein ja ehdotan, että poistatte lisätyn filtterin `'maksuturva/internal_payment_id'`, koska sitä ei saa kovin järkevästi toimimaan.

-----

Kehittelin viitenumeroasiaa eteenpäin ja sain homman toimimaan seuraavilla tempuilla.

1. Lisään Woocommerce tilaukseen uuden metan 'maksuturva_reference', joka on siis haluamani oma viitenumero ilman viimeistä tarkistenumeroa. Muodostan koko suomalaisen viitteen myös ja tallennan siitä metan 'finnish_reference_number'
2. Muokkaan `WC_Gateway_Maksuturva::create_payment_data( WC_Gateway_Maksuturva $gateway, WC_Order $order )` niin että 'pmt_reference' on haluttu ja se haetaan WC_Orderin metasta 'maksuturva_reference'. Jos metaa ei ole asetettu, käytetään oletusreferenceä
```
...
$reference        = $this->get_internal_payment_id( $order );
		if ( ! empty( $custom_reference = get_post_meta( $order_handler->get_id(), 'maksuturva_reference', true) ) ) {
			$reference = $custom_reference;
		}

		$data = [
			'pmt_keygeneration'      => $gateway->get_secret_key_version(),
			'pmt_id'                 => $payment_id,
			'pmt_orderid'            => $order_handler->get_id(),
			'pmt_reference'          => $reference,
...
```


Viitenumeron generoin pohjanumero + order_id ja tallennan sen tosiaan metaan. 

> Tervehdys, eli vielä vähän kysellään tarkennusta, kumpi olisi parempi parannus:
> a) Svean asetuksissa voi antaa "pohjanumeron", josta lähtien noita viitteitä muodostetaan... esim. asetuksissa "40000000", joten viite muodostuisi 40000000+order_id esim. 40000000+17 = 40000017 jne. Lisäksi loppuun suomalainen tarkiste.
> b) pmt_reference tulisi jostain muualta WooCommercesta, order metatiedoista? Mikä plugin tuon metatiedon asettaa?

----

Toivottavasti saitte kiinni mitä yritin selvittää. Plugarin kehitystä ajatellen en osaa suoraan arvioida, mikä olisi paras ratkaisu edetä tämän suhteen. Toivoisin, että ominaisuus saataisiin lisäosaan mukaan jollakin tavalla, sillä pidemmällä aikavälillä oma kustomiversion ylläpito käy hankalaksi.

Kiitos ja anteeksi!

**Comment by Svea-Maintainer** [comment]
Ei mitään... meillä ei muutenkaan ollut tuolle "lisäominaisuudelle", joka aiemmin lisättiin oikein testiä, joten sen toimivuutta ei ollut testattu.

Nyt tuo laajempi muutos kirjataan ylös kehitysehdotuksena ja katsotaan tarkemmin.

Tällä hetkellä asetuksissa on mahdollista asettaa maksun tunnisteelle "prefix", tässä esimerkissä 9050. Mutta nykyisellään se ei vaikuta viitteeseen. Yksi mahdollisuus voisi olla että tuo pohjanumero otetaan käyttöön myös viitenumerossa. Eli nykyisellään kun order id = 99, niin siitä muodostuu x = order id + 100. Sitten maksun tunnus on prefix+x ja viitenumero on x+tarkiste...
Maksun tunnus: 9050199
Tilausnumero: 99
Viitenumero: 1999

Jatkossa viitenumero voisi olla prefix+x+tarkiste? Mutta tosiaan tämä mahdollistaa vain sellaiset viitenumerosarjat, joiden muodostus tapahtuu maksumoduulin omien asestusten pohjalta. Joskus on ollut toivetta myös ulkoisten lisäosien laskemille sarjoille...
