### ISSUE TITLE
Checkout broken

### ISSUE THREAD

**Issue by andreibsl** [maksuturva/woocommerce_payment_module#59]
Hello,

When we activate the plugin and set everything up, all the images that should be present in the checkout page are not there.

Here is a screenshot to explain it better:

<img width="1372" alt="Screenshot 2023-12-20 at 15 21 09" src="https://github.com/maksuturva/woocommerce_payment_module/assets/154438735/129ad9a9-05d3-47c9-b70b-05121789b2c2">

Does anyone have any idea why this happens?

I've also tried with the Storefront theme and it's the same.

Thanks,

Andrei

**Comment by petemaksuturva** [comment]
Hi,
Can you please send e-mail to our technical support support(dot)payments(at)svea.fi and explain the use case of this customer more. This module is mostly meant for EUR payments within Finland. In some very rare cases it might be possible to use it for NOK currency or Norwegian customers.

**Comment by Svea-Maintainer** [comment]
NOK not supported
