### ISSUE TITLE
pmt_row_desc is not handled well

### ISSUE THREAD

**Issue by Stimppa** [maksuturva/woocommerce_payment_module#8]
If pmt_row_desc contains special characters (for example new line character) hash check could fail resulting in a fail of the entire transaction. If no product description is necessary, the problem can be fixed by changing line 175 of includes/class-wc-gateway-implementation-maksuturva.php from `$payment_row_product['pmt_row_desc']     =  WC_Utils_Maksuturva::filter_description( $description );`
to
`$payment_row_product['pmt_row_desc']     =  "-"; `

**Comment by Hene-Svea** [comment]
Released version v2.1.1 of the plugin has been tested using äöå characters in the product item. We have analyzed traffic between Woocommerce shop and the backend, and hash calculation seems to be ok.

You may test this new release version alongside the current one, and it's backward compatible down to v2.0.5, at least.

Don't hesitate to give further feedback.
