### ISSUE TITLE
Error when checking payment status in background

### ISSUE THREAD

**Issue by vvastamaki** [maksuturva/woocommerce_payment_module#9]
This error comes when plugin tries to update payment status in our shop. So basically our error log will be flooded every 5 minutes with this error.

[Mon May 06 07:55:03.756869 2019] [php7:error] [pid 20074] [client 127.0.0.1:35898]
PHP Fatal error: Uncaught TypeError: Argument 2 passed to WC_Gateway_Implementation_Maksuturva::__construct() must be an instance of WC_Order, boolean given, called in /wp-content/plugins/woocommerce_payment_module-master/includes/class-wc-payment-checker-maksuturva.php on line 109 and
defined in /wp-content/plugins/woocommerce_payment_module-master/includes/class-wc-gateway-implementation-maksuturva.php:92
Stack trace: 
#0 /wp-content/plugins/woocommerce_payment_module-master/includes/class-wc-payment-checker-maksuturva.php(109): WC_Gateway_Implementation_Maksuturva->__construct(Object(WC_Gateway_Maksuturva), false)
#1 /wp-content/plugins/woocommerce_payment_module-master/includes/class-wc-payment-checker-maksuturva.php(164): WC_Payment_Checker_Maksuturva->check_payment(Object(WC_Payment_Maksuturva))
#2 /wp-content/plugins/woocommerce_payment_module-master/wc-maksuturva.php(254): WC_Payment_Checker_Maksuturv in /wp-content/plugins/woocommerce_payment_module-master/includes/class-wc-gateway-implementation-maksuturva.php on line 92

**Comment by tlehtimaki** [comment]
Maybe that could be fixed by just adding a check  before line 109 that `$order` really is an instance of `WC_Order`? Maybe that would include doing things a bit differently in that `WC_Gateway_Implementation_Maksuturva` class.

As a reference here is the line 108 that causes the problem in my opinion:
https://github.com/maksuturva/woocommerce_payment_module/blob/831a47332c66ac419f6cd5d06b6480f5e6817f32/includes/class-wc-payment-checker-maksuturva.php#L108

**Comment by katjajohanna** [comment]
Thanks for your quick reply, @tlehtimaki. Adding the check you proposed, that `$order` really is of correct type, would prevent the fatal error. It wouldn't make the payment check work, though. The reason for the payment check is to find paid payments, which are not in paid status in the web shop.

The reason why `$order` is boolean, seems to be that action `woocommerce_after_register_post_type` is not executed. Thanks for including the link to the `wc_get_order` documentation! Will have look into that.

**Comment by Hene-Svea** [comment]
There is version 2.1.1 release now with some fixes to status queries and payment checker. For example deleted orders are removed from the status query queue to prevent sync problems.

**Comment by wiljamiwho** [comment]
Thanks for information @Hene-Svea! I'll update plugin soon, let's see if it fixes the problem :)

**Comment by vvastamaki** [comment]
Thanks for the information @Hene-Svea! I'll update plugin soon, let's see if it fixes the problem :)

**Comment by Hene-Svea** [comment]
Good. Closing the issue now. If there is still problems don't hesitate to give feedback.
